version: '3.4'

services:

  pgadmin:
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    restart: always
    ports:
      - "5450:80"
    depends_on:
      - catalog.database
      - basket.database


  catalog.database:
    container_name: catalog.database
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eshop_catalog
    restart: always
    ports:
      - "5400:5432"
    volumes:
      - catalog_db:/var/lib/postgresql/data
   
  basket.database:
    container_name: basket.database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=eshop_basket
    restart: always
    ports:
      - "5401:27017"
    volumes:
      - basket_db:/data/db

  basket.cache:
    container_name: basket.cache
    restart: always
    ports:
      - "6379:6379"


  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=catalog.database;Port=5432;Database=eshop_catalog;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "6000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - catalog.database

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=basket.database;Port=5432;Database=eshop_basket;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Cacher=basket.cache:6379
    ports:
      - "6001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - basket.database
      - basket.cache
