version: '3.4'

services:
  pgadmin:
    image: dpage/pgadmin4


  catalog.database:
    image: postgres

  basket.database:
    image: postgres


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile


volumes:
  catalog_db:
  basket_db:
