
services:
  pgadmin:
    image: dpage/pgadmin4


  catalog.database:
    image: postgres

  basket.database:
    image: mongo

  basket.cache:
    image: redis


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile


volumes:
  catalog_db:
  basket_db:
